In [1]:
## Testando o uso de 'statistics' no Python.
import statistics as estatistica

# Dados de exemplo
dados = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 10, 50, 100, 100]

# Calculando a média usando statistics
media = estatistica.mean(dados)

# Calculando a mediana usando statistics
mediana = estatistica.median(dados)

# Calculando a moda usando statistics
moda = estatistica.mode(dados)

print("A Média é",media)
print("A Mediana é",mediana)
print("A Moda é",moda)


A Média é 57.857142857142854
A Mediana é 55.0
A Moda é 100


In [2]:
import numpy as np

# Criando um array unidimensional
array_1d = np.array([1, 2, 3, 4, 5])
print("Array unidimensional:")
print(array_1d)

# Criando um array bidimensional
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nArray bidimensional:")
print(array_2d)


# Indexação em arrays unidimensionais
print("\nIndexação e Slicing em arrays unidimensionais:")
print("Primeiro elemento:", array_1d[0])
print("Último elemento:", array_1d[-1])
print("Slicing do segundo ao quarto elemento:", array_1d[1:4])

# Indexação em arrays bidimensionais
print("\nIndexação e Slicing em arrays bidimensionais:")
print("Elemento na segunda linha e terceira coluna:", array_2d[1, 2])
print("Primeira coluna:", array_2d[:, 0])
print("Última linha:", array_2d[-1, :])
print("Slicing da segunda e terceira linha e segunda coluna:", array_2d[1:3, 1])


# Operações básicas com arrays
print("\nOperações básicas com arrays:")
# Soma de elementos de um array unidimensional
print("Soma dos elementos do array unidimensional:", np.sum(array_1d))
# Soma de elementos de um array bidimensional
print("Soma dos elementos do array bidimensional:", np.sum(array_2d))
# Multiplicação de um array por um escalar
print("Multiplicação do array unidimensional por 2:", array_1d * 2)
# Multiplicação de dois arrays
print("Multiplicação elemento a elemento dos dois arrays:", array_1d * array_1d)
# Produto escalar de dois arrays
print("Produto escalar dos dois arrays:", np.dot(array_1d, array_1d))


Array unidimensional:
[1 2 3 4 5]

Array bidimensional:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Indexação e Slicing em arrays unidimensionais:
Primeiro elemento: 1
Último elemento: 5
Slicing do segundo ao quarto elemento: [2 3 4]

Indexação e Slicing em arrays bidimensionais:
Elemento na segunda linha e terceira coluna: 6
Primeira coluna: [1 4 7]
Última linha: [7 8 9]
Slicing da segunda e terceira linha e segunda coluna: [5 8]

Operações básicas com arrays:
Soma dos elementos do array unidimensional: 15
Soma dos elementos do array bidimensional: 45
Multiplicação do array unidimensional por 2: [ 2  4  6  8 10]
Multiplicação elemento a elemento dos dois arrays: [ 1  4  9 16 25]
Produto escalar dos dois arrays: 55
